###################################################
#
# Spring基础配置
#
###################################################
spring:
  application:
    name: innocence
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
    multipart:
      max-file-size: 30Mb
      max-request-size: 100Mb
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  mvc:
    servlet:
      load-on-startup: 1
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    restart:
      enabled: true
      exclude: src/main/resources/static
      additional-paths: src/main/java
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/idb?useSSL=false&useUnicode=true&characterEncoding=utf8
    password: root
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      filters: mergeStat
server:
  port: 80
  tomcat:
    uri-encoding: utf-8
mybatis:
  config-location: classpath:/mybatis-config.xml
  check-config-location: true
  type-aliases-package: com.suxia.innocence.system.sys.domain;com.suxia.innocence.system.sys.vo
  mapper-locations: classpath:/mapper/*Mapper.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  path: ../logs/innocence
  level:
    com.suxia.innocence.system: debug

